/*
 * generated by Xtext 2.44.0
 */
package geodes.sms.diningroom.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DiningRoomTextualGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class RoomElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "geodes.sms.diningroom.DiningRoomTextual.Room");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRoomAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRoomKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cFurnitureKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cFurnitureAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cFurnitureFurnitureParserRuleCall_4_2_0 = (RuleCall)cFurnitureAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cFurnitureAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cFurnitureFurnitureParserRuleCall_4_3_1_0 = (RuleCall)cFurnitureAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Room returns Room:
		//    {Room}
		//    'Room'
		//    name=EString
		//    '{'
		//        ('furniture' '{' furniture+=Furniture ( "," furniture+=Furniture)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Room}
		//'Room'
		//name=EString
		//'{'
		//    ('furniture' '{' furniture+=Furniture ( "," furniture+=Furniture)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Room}
		public Action getRoomAction_0() { return cRoomAction_0; }
		
		//'Room'
		public Keyword getRoomKeyword_1() { return cRoomKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('furniture' '{' furniture+=Furniture ( "," furniture+=Furniture)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'furniture'
		public Keyword getFurnitureKeyword_4_0() { return cFurnitureKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//furniture+=Furniture
		public Assignment getFurnitureAssignment_4_2() { return cFurnitureAssignment_4_2; }
		
		//Furniture
		public RuleCall getFurnitureFurnitureParserRuleCall_4_2_0() { return cFurnitureFurnitureParserRuleCall_4_2_0; }
		
		//( "," furniture+=Furniture)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//furniture+=Furniture
		public Assignment getFurnitureAssignment_4_3_1() { return cFurnitureAssignment_4_3_1; }
		
		//Furniture
		public RuleCall getFurnitureFurnitureParserRuleCall_4_3_1_0() { return cFurnitureFurnitureParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class FurnitureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "geodes.sms.diningroom.DiningRoomTextual.Furniture");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTableParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cChairParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Furniture returns Furniture:
		//    Table | Chair;
		@Override public ParserRule getRule() { return rule; }
		
		//Table | Chair
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Table
		public RuleCall getTableParserRuleCall_0() { return cTableParserRuleCall_0; }
		
		//Chair
		public RuleCall getChairParserRuleCall_1() { return cChairParserRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "geodes.sms.diningroom.DiningRoomTextual.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class TableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "geodes.sms.diningroom.DiningRoomTextual.Table");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTableAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTableKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cXKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cXAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cXEIntParserRuleCall_4_1_0 = (RuleCall)cXAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cYKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cYAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cYEIntParserRuleCall_5_1_0 = (RuleCall)cYAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cAroundKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cAroundAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cAroundChairCrossReference_6_2_0 = (CrossReference)cAroundAssignment_6_2.eContents().get(0);
		private final RuleCall cAroundChairEStringParserRuleCall_6_2_0_1 = (RuleCall)cAroundChairCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cAroundAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cAroundChairCrossReference_6_3_1_0 = (CrossReference)cAroundAssignment_6_3_1.eContents().get(0);
		private final RuleCall cAroundChairEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cAroundChairCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Table returns Table:
		//    {Table}
		//    'Table'
		//    name=EString
		//    '{'
		//        ('x' x=EInt)?
		//        ('y' y=EInt)?
		//        ('around' '(' around+=[Chair|EString] ( "," around+=[Chair|EString])* ')' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Table}
		//'Table'
		//name=EString
		//'{'
		//    ('x' x=EInt)?
		//    ('y' y=EInt)?
		//    ('around' '(' around+=[Chair|EString] ( "," around+=[Chair|EString])* ')' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Table}
		public Action getTableAction_0() { return cTableAction_0; }
		
		//'Table'
		public Keyword getTableKeyword_1() { return cTableKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('x' x=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'x'
		public Keyword getXKeyword_4_0() { return cXKeyword_4_0; }
		
		//x=EInt
		public Assignment getXAssignment_4_1() { return cXAssignment_4_1; }
		
		//EInt
		public RuleCall getXEIntParserRuleCall_4_1_0() { return cXEIntParserRuleCall_4_1_0; }
		
		//('y' y=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'y'
		public Keyword getYKeyword_5_0() { return cYKeyword_5_0; }
		
		//y=EInt
		public Assignment getYAssignment_5_1() { return cYAssignment_5_1; }
		
		//EInt
		public RuleCall getYEIntParserRuleCall_5_1_0() { return cYEIntParserRuleCall_5_1_0; }
		
		//('around' '(' around+=[Chair|EString] ( "," around+=[Chair|EString])* ')' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'around'
		public Keyword getAroundKeyword_6_0() { return cAroundKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//around+=[Chair|EString]
		public Assignment getAroundAssignment_6_2() { return cAroundAssignment_6_2; }
		
		//[Chair|EString]
		public CrossReference getAroundChairCrossReference_6_2_0() { return cAroundChairCrossReference_6_2_0; }
		
		//EString
		public RuleCall getAroundChairEStringParserRuleCall_6_2_0_1() { return cAroundChairEStringParserRuleCall_6_2_0_1; }
		
		//( "," around+=[Chair|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//around+=[Chair|EString]
		public Assignment getAroundAssignment_6_3_1() { return cAroundAssignment_6_3_1; }
		
		//[Chair|EString]
		public CrossReference getAroundChairCrossReference_6_3_1_0() { return cAroundChairCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getAroundChairEStringParserRuleCall_6_3_1_0_1() { return cAroundChairEStringParserRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ChairElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "geodes.sms.diningroom.DiningRoomTextual.Chair");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cChairAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cChairKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOrderKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cOrderAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cOrderEIntParserRuleCall_4_1_0 = (RuleCall)cOrderAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Chair returns Chair:
		//    {Chair}
		//    'Chair'
		//    name=EString
		//    '{'
		//        ('order' order=EInt)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Chair}
		//'Chair'
		//name=EString
		//'{'
		//    ('order' order=EInt)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Chair}
		public Action getChairAction_0() { return cChairAction_0; }
		
		//'Chair'
		public Keyword getChairKeyword_1() { return cChairKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('order' order=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'order'
		public Keyword getOrderKeyword_4_0() { return cOrderKeyword_4_0; }
		
		//order=EInt
		public Assignment getOrderAssignment_4_1() { return cOrderAssignment_4_1; }
		
		//EInt
		public RuleCall getOrderEIntParserRuleCall_4_1_0() { return cOrderEIntParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "geodes.sms.diningroom.DiningRoomTextual.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	
	private final RoomElements pRoom;
	private final FurnitureElements pFurniture;
	private final EStringElements pEString;
	private final TableElements pTable;
	private final ChairElements pChair;
	private final EIntElements pEInt;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DiningRoomTextualGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRoom = new RoomElements();
		this.pFurniture = new FurnitureElements();
		this.pEString = new EStringElements();
		this.pTable = new TableElements();
		this.pChair = new ChairElements();
		this.pEInt = new EIntElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("geodes.sms.diningroom.DiningRoomTextual".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Room returns Room:
	//    {Room}
	//    'Room'
	//    name=EString
	//    '{'
	//        ('furniture' '{' furniture+=Furniture ( "," furniture+=Furniture)* '}' )?
	//    '}';
	public RoomElements getRoomAccess() {
		return pRoom;
	}
	
	public ParserRule getRoomRule() {
		return getRoomAccess().getRule();
	}
	
	//Furniture returns Furniture:
	//    Table | Chair;
	public FurnitureElements getFurnitureAccess() {
		return pFurniture;
	}
	
	public ParserRule getFurnitureRule() {
		return getFurnitureAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Table returns Table:
	//    {Table}
	//    'Table'
	//    name=EString
	//    '{'
	//        ('x' x=EInt)?
	//        ('y' y=EInt)?
	//        ('around' '(' around+=[Chair|EString] ( "," around+=[Chair|EString])* ')' )?
	//    '}';
	public TableElements getTableAccess() {
		return pTable;
	}
	
	public ParserRule getTableRule() {
		return getTableAccess().getRule();
	}
	
	//Chair returns Chair:
	//    {Chair}
	//    'Chair'
	//    name=EString
	//    '{'
	//        ('order' order=EInt)?
	//    '}';
	public ChairElements getChairAccess() {
		return pChair;
	}
	
	public ParserRule getChairRule() {
		return getChairAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
