/*
 * generated by Xtext 2.44.0
 */
package holt.travis.ift6253.formatting2

import com.google.inject.Inject
import holt.travis.ift6253.mindMap.MindMap
import holt.travis.ift6253.services.MindMapGrammarAccess
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import holt.travis.ift6253.mindMap.Topic

class MindMapFormatter extends AbstractFormatter2 {
	
	@Inject extension MindMapGrammarAccess

	def dispatch void format(MindMap mindMap, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (node : mindMap.roots) {
			node.format
		}
	}

	def dispatch void format(Topic node, extension IFormattableDocument document) {
		val open = node.regionFor.keyword("{")
		val close = node.regionFor.keyword("}")

		open.append[newLine]
		close.append[newLine]
		interior(open, close)[indent]

		for (child : node.children) {
			child.format
		}
	}
	
}
