/*
 * generated by Xtext 2.44.0
 */
package geodes.sms.diningroom.ui.tests;

import com.google.inject.Injector;
import diningRoomTextual.ui.internal.DiningRoomTextualActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DiningRoomTextualUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DiningRoomTextualActivator.getInstance().getInjector("geodes.sms.diningroom.DiningRoomTextual");
	}

}
