/*
 * generated by Xtext 2.44.0
 */
package geodes.sms.diningroom.parser.antlr;

import com.google.inject.Inject;
import geodes.sms.diningroom.parser.antlr.internal.InternalDiningRoomTextualParser;
import geodes.sms.diningroom.services.DiningRoomTextualGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DiningRoomTextualParser extends AbstractAntlrParser {

	@Inject
	private DiningRoomTextualGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDiningRoomTextualParser createParser(XtextTokenStream stream) {
		return new InternalDiningRoomTextualParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Room";
	}

	public DiningRoomTextualGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DiningRoomTextualGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
