/*
 * generated by Xtext 2.44.0
 */
package geodes.sms.diningroom.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DiningRoomTextualAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("geodes/sms/diningroom/parser/antlr/internal/InternalDiningRoomTextual.tokens");
	}
}
