/*
 * generated by Xtext 2.44.0
 */
package holt.travis.ift6253.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class MindMapOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
