/*
 * generated by Xtext 2.44.0
 */
grammar InternalDiningRoomTextual;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package geodes.sms.diningroom.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package geodes.sms.diningroom.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import geodes.sms.diningroom.services.DiningRoomTextualGrammarAccess;

}

@parser::members {

 	private DiningRoomTextualGrammarAccess grammarAccess;

    public InternalDiningRoomTextualParser(TokenStream input, DiningRoomTextualGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "Room";
   	}

   	@Override
   	protected DiningRoomTextualGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleRoom
entryRuleRoom returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRoomRule()); }
	iv_ruleRoom=ruleRoom
	{ $current=$iv_ruleRoom.current; }
	EOF;

// Rule Room
ruleRoom returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getRoomAccess().getRoomAction_0(),
					$current);
			}
		)
		otherlv_1='Room'
		{
			newLeafNode(otherlv_1, grammarAccess.getRoomAccess().getRoomKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getRoomAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getRoomRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"geodes.sms.diningroom.DiningRoomTextual.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='{'
		{
			newLeafNode(otherlv_3, grammarAccess.getRoomAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			otherlv_4='furniture'
			{
				newLeafNode(otherlv_4, grammarAccess.getRoomAccess().getFurnitureKeyword_4_0());
			}
			otherlv_5='{'
			{
				newLeafNode(otherlv_5, grammarAccess.getRoomAccess().getLeftCurlyBracketKeyword_4_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getRoomAccess().getFurnitureFurnitureParserRuleCall_4_2_0());
					}
					lv_furniture_6_0=ruleFurniture
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getRoomRule());
						}
						add(
							$current,
							"furniture",
							lv_furniture_6_0,
							"geodes.sms.diningroom.DiningRoomTextual.Furniture");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_7=','
				{
					newLeafNode(otherlv_7, grammarAccess.getRoomAccess().getCommaKeyword_4_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getRoomAccess().getFurnitureFurnitureParserRuleCall_4_3_1_0());
						}
						lv_furniture_8_0=ruleFurniture
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getRoomRule());
							}
							add(
								$current,
								"furniture",
								lv_furniture_8_0,
								"geodes.sms.diningroom.DiningRoomTextual.Furniture");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_9='}'
			{
				newLeafNode(otherlv_9, grammarAccess.getRoomAccess().getRightCurlyBracketKeyword_4_4());
			}
		)?
		otherlv_10='}'
		{
			newLeafNode(otherlv_10, grammarAccess.getRoomAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleFurniture
entryRuleFurniture returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getFurnitureRule()); }
	iv_ruleFurniture=ruleFurniture
	{ $current=$iv_ruleFurniture.current; }
	EOF;

// Rule Furniture
ruleFurniture returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getFurnitureAccess().getTableParserRuleCall_0());
		}
		this_Table_0=ruleTable
		{
			$current = $this_Table_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getFurnitureAccess().getChairParserRuleCall_1());
		}
		this_Chair_1=ruleChair
		{
			$current = $this_Chair_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleEString
entryRuleEString returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEStringRule()); }
	iv_ruleEString=ruleEString
	{ $current=$iv_ruleEString.current.getText(); }
	EOF;

// Rule EString
ruleEString returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_STRING_0=RULE_STRING
		{
			$current.merge(this_STRING_0);
		}
		{
			newLeafNode(this_STRING_0, grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0());
		}
		    |
		this_ID_1=RULE_ID
		{
			$current.merge(this_ID_1);
		}
		{
			newLeafNode(this_ID_1, grammarAccess.getEStringAccess().getIDTerminalRuleCall_1());
		}
	)
;

// Entry rule entryRuleTable
entryRuleTable returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTableRule()); }
	iv_ruleTable=ruleTable
	{ $current=$iv_ruleTable.current; }
	EOF;

// Rule Table
ruleTable returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getTableAccess().getTableAction_0(),
					$current);
			}
		)
		otherlv_1='Table'
		{
			newLeafNode(otherlv_1, grammarAccess.getTableAccess().getTableKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getTableAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getTableRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"geodes.sms.diningroom.DiningRoomTextual.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='{'
		{
			newLeafNode(otherlv_3, grammarAccess.getTableAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			otherlv_4='x'
			{
				newLeafNode(otherlv_4, grammarAccess.getTableAccess().getXKeyword_4_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getTableAccess().getXEIntParserRuleCall_4_1_0());
					}
					lv_x_5_0=ruleEInt
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getTableRule());
						}
						set(
							$current,
							"x",
							lv_x_5_0,
							"geodes.sms.diningroom.DiningRoomTextual.EInt");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_6='y'
			{
				newLeafNode(otherlv_6, grammarAccess.getTableAccess().getYKeyword_5_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getTableAccess().getYEIntParserRuleCall_5_1_0());
					}
					lv_y_7_0=ruleEInt
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getTableRule());
						}
						set(
							$current,
							"y",
							lv_y_7_0,
							"geodes.sms.diningroom.DiningRoomTextual.EInt");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_8='around'
			{
				newLeafNode(otherlv_8, grammarAccess.getTableAccess().getAroundKeyword_6_0());
			}
			otherlv_9='('
			{
				newLeafNode(otherlv_9, grammarAccess.getTableAccess().getLeftParenthesisKeyword_6_1());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getTableRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getTableAccess().getAroundChairCrossReference_6_2_0());
					}
					ruleEString
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_11=','
				{
					newLeafNode(otherlv_11, grammarAccess.getTableAccess().getCommaKeyword_6_3_0());
				}
				(
					(
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getTableRule());
							}
						}
						{
							newCompositeNode(grammarAccess.getTableAccess().getAroundChairCrossReference_6_3_1_0());
						}
						ruleEString
						{
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_13=')'
			{
				newLeafNode(otherlv_13, grammarAccess.getTableAccess().getRightParenthesisKeyword_6_4());
			}
		)?
		otherlv_14='}'
		{
			newLeafNode(otherlv_14, grammarAccess.getTableAccess().getRightCurlyBracketKeyword_7());
		}
	)
;

// Entry rule entryRuleChair
entryRuleChair returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getChairRule()); }
	iv_ruleChair=ruleChair
	{ $current=$iv_ruleChair.current; }
	EOF;

// Rule Chair
ruleChair returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getChairAccess().getChairAction_0(),
					$current);
			}
		)
		otherlv_1='Chair'
		{
			newLeafNode(otherlv_1, grammarAccess.getChairAccess().getChairKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getChairAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getChairRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"geodes.sms.diningroom.DiningRoomTextual.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='{'
		{
			newLeafNode(otherlv_3, grammarAccess.getChairAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			otherlv_4='order'
			{
				newLeafNode(otherlv_4, grammarAccess.getChairAccess().getOrderKeyword_4_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getChairAccess().getOrderEIntParserRuleCall_4_1_0());
					}
					lv_order_5_0=ruleEInt
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getChairRule());
						}
						set(
							$current,
							"order",
							lv_order_5_0,
							"geodes.sms.diningroom.DiningRoomTextual.EInt");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_6='}'
		{
			newLeafNode(otherlv_6, grammarAccess.getChairAccess().getRightCurlyBracketKeyword_5());
		}
	)
;

// Entry rule entryRuleEInt
entryRuleEInt returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEIntRule()); }
	iv_ruleEInt=ruleEInt
	{ $current=$iv_ruleEInt.current.getText(); }
	EOF;

// Rule EInt
ruleEInt returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			kw='-'
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getEIntAccess().getHyphenMinusKeyword_0());
			}
		)?
		this_INT_1=RULE_INT
		{
			$current.merge(this_INT_1);
		}
		{
			newLeafNode(this_INT_1, grammarAccess.getEIntAccess().getINTTerminalRuleCall_1());
		}
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
