// name the grammar and build on xtext lexing
grammar holt.travis.ift6253.MindMap with org.eclipse.xtext.common.Terminals

// infer new ecore metamodel from this grammar
generate mindMap "http://www.travis.holt/ift6253/MindMap"


// entry rule
MindMap:
	// containment feature
	roots+=Root+; // one or more
	
fragment NodeFeatures *:
	name=ID ('{' children+=Node* '}');
	
Node:
	{Node} NodeFeatures;
	
Root returns Node:
	{Root} NodeFeatures;
