/*
 * generated by Xtext 2.44.0
 */
package holt.travis.ift6253;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MindMapStandaloneSetup extends MindMapStandaloneSetupGenerated {

	public static void doSetup() {
		new MindMapStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
