/*
 * generated by Xtext 2.44.0
 */
package geodes.sms.diningroom.serializer;

import DiningRoom.Chair;
import DiningRoom.DiningRoomPackage;
import DiningRoom.Room;
import DiningRoom.Table;
import com.google.inject.Inject;
import geodes.sms.diningroom.services.DiningRoomTextualGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;

@SuppressWarnings("all")
public class DiningRoomTextualSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private DiningRoomTextualGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == DiningRoomPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case DiningRoomPackage.CHAIR:
				sequence_Chair(context, (Chair) semanticObject); 
				return; 
			case DiningRoomPackage.ROOM:
				sequence_Room(context, (Room) semanticObject); 
				return; 
			case DiningRoomPackage.TABLE:
				sequence_Table(context, (Table) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Furniture returns Chair
	 *     Chair returns Chair
	 *
	 * Constraint:
	 *     (name=EString order=EInt?)
	 * </pre>
	 */
	protected void sequence_Chair(ISerializationContext context, Chair semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Room returns Room
	 *
	 * Constraint:
	 *     (name=EString (furniture+=Furniture furniture+=Furniture*)?)
	 * </pre>
	 */
	protected void sequence_Room(ISerializationContext context, Room semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Furniture returns Table
	 *     Table returns Table
	 *
	 * Constraint:
	 *     (name=EString x=EInt? y=EInt? (around+=[Chair|EString] around+=[Chair|EString]*)?)
	 * </pre>
	 */
	protected void sequence_Table(ISerializationContext context, Table semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
