/*
 * generated by Xtext 2.44.0
 */
package holt.travis.ift6253.tests

import com.google.inject.Inject
import holt.travis.ift6253.mindMap.MindMap
import holt.travis.ift6253.mindMap.MindMapPackage
import holt.travis.ift6253.validation.MindMapValidator
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(MindMapInjectorProvider)
class MindMapParsingTest {
	@Inject
	ParseHelper<MindMap> parseHelper

	@Inject
	extension ValidationTestHelper;

	@Test
	def void loadModelEmptyMindMap() {
		val result = parseHelper.parse('''
			mindmap mde_course {}
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty);
	}

	@Test
	def void loadModelWithOneTopic() {
		val result = parseHelper.parse('''
			mindmap mde_course {
				- dummy {}
			}
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty);
	}

	@Test
	def void loadModelWithOneTopicWithoutBraces() {
		val result = parseHelper.parse('''
			mindmap mde_course {
				- dummy
			}
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty);
	}

	@Test
	def void loadModelWithOneTag() {
		val result = parseHelper.parse('''
			mindmap mde_course (tag TAG1) {}
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty);
	}

	@Test
	def void loadModelWithMultipleTags() {
		val result = parseHelper.parse('''
			mindmap mde_course (tag TAG1, tag TAG2) {}
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty);
	}

	@Test
	def void loadModelWithTaggedTopic() {
		val result = parseHelper.parse('''
			mindmap mde_course (tag DUMMY) {
				- my_topic <DUMMY>
			}
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty);
	}

	@Test
	def void loadModelWithMultiTaggedTopic() {
		val result = parseHelper.parse('''
			mindmap mde_course (tag DUMMY1, tag DUMMY2) {
				- my_topic <DUMMY1> <DUMMY2>
			}
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty);
	}

	@Test
	def void loadModelWithMultipleRoots() {
		val result = parseHelper.parse('''
			mindmap mde_course {
				- dummy1
				- dummy2
			}
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty);
	}

	@Test
	def void loadModelWithDeeperRootFails() {
		val result = parseHelper.parse('''
			mindmap mde_course {
				-> dummy
			}
		''')
		result.assertError(MindMapPackage.Literals.TOPIC, MindMapValidator.DEEPER_AT_ROOT);
	}

	@Test
	def void loadModelWithDeeperTopic() {
		val result = parseHelper.parse('''
			mindmap mde_course {
				- parent {
					-> deeper_child
				}
			}
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty);
	}


//	@Test
	def void loadModelFullFeatured() {
		val result = parseHelper.parse('''
			mindmap mde_course (tag STAR, tag QUESTION) {
			    - class (H) {
			        description: "text description of topic"
			        view {
			            color: "#0000FF"
			        }
			        -> attendance <STAR> <QUESTION> (H)
			        - active_learning {
			            - take_notes
			            - clarify_with_chat
			        }
			    }
			    - work (M) {
			        - readings (L) {
			            -> todo
			            -> done
			            - projects {
			                - main <STAR> {
			                    -> find_partner {
			                        - suggest_topic <QUESTION>
			                        -> talk_to_someone
			                    }
			                }
			            }
			        }
			        - homework
			        - tool_tutorials
			    }
			}
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
