/*
 * generated by Xtext 2.44.0
 */
package holt.travis.ift6253.tests

import com.google.inject.Inject
import holt.travis.ift6253.mindMap.MindMap
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(MindMapInjectorProvider)
class MindMapParsingTest {
	@Inject
	ParseHelper<MindMap> parseHelper
	
	@Test
	def void loadModelEmptyMindMap() {
		val result = parseHelper.parse('''
			mindmap mde_course {} 
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
//	@Test
	def void loadModelFullFeatured() {
		val result = parseHelper.parse('''
			mindmap mde_course (tag STAR, tag QUESTION) {
			    - class (H) {
			        description: "text description of topic"
			        view {
			            color: "#0000FF"
			        }
			        -> attendance <STAR> <QUESTION> (H)
			        - active_learning {
			            - take_notes
			            - clarify_with_chat
			        }
			    }
			    - work (M) {
			        - readings (L) {
			            -> todo
			            -> done
			            - projects {
			                - main <STAR> {
			                    -> find_partner {
			                        - suggest_topic <QUESTION>
			                        -> talk_to_someone
			                    }
			                }
			            }
			        }
			        - homework
			        - tool_tutorials
			    }
			} 
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
