/*
 * generated by Xtext 2.44.0
 */
package holt.travis.ift6253.formatting2

import holt.travis.ift6253.mindMap.MindMap
import holt.travis.ift6253.mindMap.MindMapPackage
import holt.travis.ift6253.mindMap.Tag
import holt.travis.ift6253.mindMap.Topic
import holt.travis.ift6253.mindMap.View
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import org.eclipse.xtext.formatting2.regionaccess.ISemanticRegion

class MindMapFormatter extends AbstractFormatter2 {

	def dispatch void format(MindMap mindMap, extension IFormattableDocument document) {
		val open = mindMap.regionFor.keyword("{")
		val close = mindMap.regionFor.keyword("}")

		//// header
		// name
		mindMap.regionFor.feature(MindMapPackage.Literals.MIND_MAP__NAME).prepend[oneSpace]

		// tags
		val paramOpen = mindMap.regionFor.keyword("(")
		val paramClose = mindMap.regionFor.keyword(")")
		if (paramOpen !== null && paramClose !== null) {
			paramOpen.prepend[oneSpace]
			paramOpen.append[noSpace]
			paramClose.prepend[noSpace]
		}
		for (comma : mindMap.regionFor.keywords(",")) {
			comma.prepend[noSpace]
			comma.append[oneSpace]
		}
		for (tag : mindMap.tags) {
			tag.format
		}

		// opening brace
		if (open !== null) {
			open.prepend[oneSpace]
		}

		//// contents
		indentBraces(open, close, document)

		for (topic : mindMap.roots) {
			topic.prepend[newLine]
			topic.format
		}
	}

	def dispatch void format(Tag tag, extension IFormattableDocument document) {
		tag.regionFor.feature(MindMapPackage.Literals.TAG__NAME).prepend[oneSpace]
	}

	def dispatch void format(Topic topic, extension IFormattableDocument document) {
		val open = topic.regionFor.keyword("{")
		val close = topic.regionFor.keyword("}")

		//// header 
		// exactly one space between each header element
		topic.regionFor.feature(MindMapPackage.Literals.TOPIC__NAME).prepend[oneSpace]

		// tags
		for (angleBracket : topic.regionFor.keywords("<")) {
			angleBracket.prepend[oneSpace]
		}

		// priority
		val priorityOpenParen = topic.regionFor.keyword("(")
		if (priorityOpenParen !== null) {
			priorityOpenParen.prepend[oneSpace]
		}
		
		// opening brace
		if (open !== null) {
			open.prepend[oneSpace]
		}
		
		//// contents
		indentBraces(open, close, document)
		
		// references: each "* related_topic" on its own line
		for (asterisk : topic.regionFor.keywords("*")) {
			asterisk.prepend[newLine]
		}
		for (relatedRef : topic.regionFor.features(MindMapPackage.Literals.TOPIC__RELATED)) {
			relatedRef.prepend[oneSpace]
		}

		topic.view.format

		for (child : topic.children) {
			child.prepend[newLine]
			child.format
		}
	}

	def dispatch void format(View view, extension IFormattableDocument document) {
		indentBraces(view.regionFor.keyword("{"), view.regionFor.keyword("}"), document)
	}

	private def void indentBraces(ISemanticRegion open, ISemanticRegion close, extension IFormattableDocument document) {
		// `Topic` braces are optional
		if (open === null || close === null) {
			return
		}
		open.append[newLine]
		interior(open, close)[indent]
		close.prepend[newLine]
	}

}
