/*
 * generated by Xtext 2.44.0
 */
package holt.travis.ift6253.formatting2

import holt.travis.ift6253.mindMap.MindMap
import holt.travis.ift6253.mindMap.MindMapPackage
import holt.travis.ift6253.mindMap.Topic
import holt.travis.ift6253.mindMap.View
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import org.eclipse.xtext.formatting2.regionaccess.ISemanticRegion

class MindMapFormatter extends AbstractFormatter2 {

	def dispatch void format(MindMap mindMap, extension IFormattableDocument document) {
		indentBraces(mindMap.regionFor.keyword("{"), mindMap.regionFor.keyword("}"), document)

		for (topic : mindMap.roots) {
			topic.prepend[newLine]
			topic.format
		}
	}

	def dispatch void format(Topic topic, extension IFormattableDocument document) {
		val open = topic.regionFor.keyword("{")
		val close = topic.regionFor.keyword("}")
		indentBraces(open, close, document)

		// exactly one space between each header element
		topic.regionFor.feature(MindMapPackage.Literals.TOPIC__NAME).prepend[oneSpace]

		// tags
		for (angleBracket : topic.regionFor.keywords("<")) {
			angleBracket.prepend[oneSpace]
		}

		// priority
		val priorityOpenParen = topic.regionFor.keyword("(")
		if (priorityOpenParen !== null) {
			priorityOpenParen.prepend[oneSpace]
		}
		
		// references
		for (asterisk : topic.regionFor.keywords("*")) {
			asterisk.prepend[oneSpace]
		}

		if (open !== null) {
			open.prepend[oneSpace]
		}

		topic.view.format

		for (child : topic.children) {
			child.prepend[newLine]
			child.format
		}
	}

	def dispatch void format(View view, extension IFormattableDocument document) {
		indentBraces(view.regionFor.keyword("{"), view.regionFor.keyword("}"), document)
	}

	private def void indentBraces(ISemanticRegion open, ISemanticRegion close, extension IFormattableDocument document) {
		// `Topic` braces are optional
		if (open === null || close === null) {
			return
		}
		open.append[newLine]
		interior(open, close)[indent]
		close.prepend[newLine]
	}

}
