/*
 * generated by Xtext 2.44.0
 */
package geodes.sms.diningroom.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class DiningRoomTextualProposalProvider extends AbstractDiningRoomTextualProposalProvider {
}
