/*
 * generated by Xtext 2.44.0
 */
package geodes.sms.diningroom.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import geodes.sms.diningroom.DiningRoomTextualRuntimeModule;
import geodes.sms.diningroom.DiningRoomTextualStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DiningRoomTextualIdeSetup extends DiningRoomTextualStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DiningRoomTextualRuntimeModule(), new DiningRoomTextualIdeModule()));
	}
	
}
