/*
 * generated by Xtext 2.44.0
 */
grammar InternalDiningRoomTextual;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package geodes.sms.diningroom.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package geodes.sms.diningroom.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import geodes.sms.diningroom.services.DiningRoomTextualGrammarAccess;

}
@parser::members {
	private DiningRoomTextualGrammarAccess grammarAccess;

	public void setGrammarAccess(DiningRoomTextualGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleRoom
entryRuleRoom
:
{ before(grammarAccess.getRoomRule()); }
	 ruleRoom
{ after(grammarAccess.getRoomRule()); } 
	 EOF 
;

// Rule Room
ruleRoom 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getRoomAccess().getGroup()); }
		(rule__Room__Group__0)
		{ after(grammarAccess.getRoomAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleFurniture
entryRuleFurniture
:
{ before(grammarAccess.getFurnitureRule()); }
	 ruleFurniture
{ after(grammarAccess.getFurnitureRule()); } 
	 EOF 
;

// Rule Furniture
ruleFurniture 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getFurnitureAccess().getAlternatives()); }
		(rule__Furniture__Alternatives)
		{ after(grammarAccess.getFurnitureAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEString
entryRuleEString
:
{ before(grammarAccess.getEStringRule()); }
	 ruleEString
{ after(grammarAccess.getEStringRule()); } 
	 EOF 
;

// Rule EString
ruleEString 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEStringAccess().getAlternatives()); }
		(rule__EString__Alternatives)
		{ after(grammarAccess.getEStringAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleTable
entryRuleTable
:
{ before(grammarAccess.getTableRule()); }
	 ruleTable
{ after(grammarAccess.getTableRule()); } 
	 EOF 
;

// Rule Table
ruleTable 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getTableAccess().getGroup()); }
		(rule__Table__Group__0)
		{ after(grammarAccess.getTableAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleChair
entryRuleChair
:
{ before(grammarAccess.getChairRule()); }
	 ruleChair
{ after(grammarAccess.getChairRule()); } 
	 EOF 
;

// Rule Chair
ruleChair 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getChairAccess().getGroup()); }
		(rule__Chair__Group__0)
		{ after(grammarAccess.getChairAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEInt
entryRuleEInt
:
{ before(grammarAccess.getEIntRule()); }
	 ruleEInt
{ after(grammarAccess.getEIntRule()); } 
	 EOF 
;

// Rule EInt
ruleEInt 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEIntAccess().getGroup()); }
		(rule__EInt__Group__0)
		{ after(grammarAccess.getEIntAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Furniture__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getFurnitureAccess().getTableParserRuleCall_0()); }
		ruleTable
		{ after(grammarAccess.getFurnitureAccess().getTableParserRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getFurnitureAccess().getChairParserRuleCall_1()); }
		ruleChair
		{ after(grammarAccess.getFurnitureAccess().getChairParserRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EString__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0()); }
		RULE_STRING
		{ after(grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getEStringAccess().getIDTerminalRuleCall_1()); }
		RULE_ID
		{ after(grammarAccess.getEStringAccess().getIDTerminalRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Room__Group__0__Impl
	rule__Room__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRoomAccess().getRoomAction_0()); }
	()
	{ after(grammarAccess.getRoomAccess().getRoomAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Room__Group__1__Impl
	rule__Room__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRoomAccess().getRoomKeyword_1()); }
	'Room'
	{ after(grammarAccess.getRoomAccess().getRoomKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Room__Group__2__Impl
	rule__Room__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRoomAccess().getNameAssignment_2()); }
	(rule__Room__NameAssignment_2)
	{ after(grammarAccess.getRoomAccess().getNameAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Room__Group__3__Impl
	rule__Room__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRoomAccess().getLeftCurlyBracketKeyword_3()); }
	'{'
	{ after(grammarAccess.getRoomAccess().getLeftCurlyBracketKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Room__Group__4__Impl
	rule__Room__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRoomAccess().getGroup_4()); }
	(rule__Room__Group_4__0)?
	{ after(grammarAccess.getRoomAccess().getGroup_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Room__Group__5__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRoomAccess().getRightCurlyBracketKeyword_5()); }
	'}'
	{ after(grammarAccess.getRoomAccess().getRightCurlyBracketKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Room__Group_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Room__Group_4__0__Impl
	rule__Room__Group_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRoomAccess().getFurnitureKeyword_4_0()); }
	'furniture'
	{ after(grammarAccess.getRoomAccess().getFurnitureKeyword_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Room__Group_4__1__Impl
	rule__Room__Group_4__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRoomAccess().getLeftCurlyBracketKeyword_4_1()); }
	'{'
	{ after(grammarAccess.getRoomAccess().getLeftCurlyBracketKeyword_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group_4__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Room__Group_4__2__Impl
	rule__Room__Group_4__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group_4__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRoomAccess().getFurnitureAssignment_4_2()); }
	(rule__Room__FurnitureAssignment_4_2)
	{ after(grammarAccess.getRoomAccess().getFurnitureAssignment_4_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group_4__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Room__Group_4__3__Impl
	rule__Room__Group_4__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group_4__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRoomAccess().getGroup_4_3()); }
	(rule__Room__Group_4_3__0)*
	{ after(grammarAccess.getRoomAccess().getGroup_4_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group_4__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Room__Group_4__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group_4__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRoomAccess().getRightCurlyBracketKeyword_4_4()); }
	'}'
	{ after(grammarAccess.getRoomAccess().getRightCurlyBracketKeyword_4_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Room__Group_4_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Room__Group_4_3__0__Impl
	rule__Room__Group_4_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group_4_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRoomAccess().getCommaKeyword_4_3_0()); }
	','
	{ after(grammarAccess.getRoomAccess().getCommaKeyword_4_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group_4_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Room__Group_4_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__Group_4_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getRoomAccess().getFurnitureAssignment_4_3_1()); }
	(rule__Room__FurnitureAssignment_4_3_1)
	{ after(grammarAccess.getRoomAccess().getFurnitureAssignment_4_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Table__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group__0__Impl
	rule__Table__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getTableAction_0()); }
	()
	{ after(grammarAccess.getTableAccess().getTableAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group__1__Impl
	rule__Table__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getTableKeyword_1()); }
	'Table'
	{ after(grammarAccess.getTableAccess().getTableKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group__2__Impl
	rule__Table__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getNameAssignment_2()); }
	(rule__Table__NameAssignment_2)
	{ after(grammarAccess.getTableAccess().getNameAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group__3__Impl
	rule__Table__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getLeftCurlyBracketKeyword_3()); }
	'{'
	{ after(grammarAccess.getTableAccess().getLeftCurlyBracketKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group__4__Impl
	rule__Table__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getGroup_4()); }
	(rule__Table__Group_4__0)?
	{ after(grammarAccess.getTableAccess().getGroup_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group__5__Impl
	rule__Table__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getGroup_5()); }
	(rule__Table__Group_5__0)?
	{ after(grammarAccess.getTableAccess().getGroup_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group__6
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group__6__Impl
	rule__Table__Group__7
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group__6__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getGroup_6()); }
	(rule__Table__Group_6__0)?
	{ after(grammarAccess.getTableAccess().getGroup_6()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group__7
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group__7__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group__7__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getRightCurlyBracketKeyword_7()); }
	'}'
	{ after(grammarAccess.getTableAccess().getRightCurlyBracketKeyword_7()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Table__Group_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group_4__0__Impl
	rule__Table__Group_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getXKeyword_4_0()); }
	'x'
	{ after(grammarAccess.getTableAccess().getXKeyword_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group_4__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getXAssignment_4_1()); }
	(rule__Table__XAssignment_4_1)
	{ after(grammarAccess.getTableAccess().getXAssignment_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Table__Group_5__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group_5__0__Impl
	rule__Table__Group_5__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_5__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getYKeyword_5_0()); }
	'y'
	{ after(grammarAccess.getTableAccess().getYKeyword_5_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_5__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group_5__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_5__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getYAssignment_5_1()); }
	(rule__Table__YAssignment_5_1)
	{ after(grammarAccess.getTableAccess().getYAssignment_5_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Table__Group_6__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group_6__0__Impl
	rule__Table__Group_6__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_6__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getAroundKeyword_6_0()); }
	'around'
	{ after(grammarAccess.getTableAccess().getAroundKeyword_6_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_6__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group_6__1__Impl
	rule__Table__Group_6__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_6__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getLeftParenthesisKeyword_6_1()); }
	'('
	{ after(grammarAccess.getTableAccess().getLeftParenthesisKeyword_6_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_6__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group_6__2__Impl
	rule__Table__Group_6__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_6__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getAroundAssignment_6_2()); }
	(rule__Table__AroundAssignment_6_2)
	{ after(grammarAccess.getTableAccess().getAroundAssignment_6_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_6__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group_6__3__Impl
	rule__Table__Group_6__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_6__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getGroup_6_3()); }
	(rule__Table__Group_6_3__0)*
	{ after(grammarAccess.getTableAccess().getGroup_6_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_6__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group_6__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_6__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getRightParenthesisKeyword_6_4()); }
	')'
	{ after(grammarAccess.getTableAccess().getRightParenthesisKeyword_6_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Table__Group_6_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group_6_3__0__Impl
	rule__Table__Group_6_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_6_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getCommaKeyword_6_3_0()); }
	','
	{ after(grammarAccess.getTableAccess().getCommaKeyword_6_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_6_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Table__Group_6_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__Group_6_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getTableAccess().getAroundAssignment_6_3_1()); }
	(rule__Table__AroundAssignment_6_3_1)
	{ after(grammarAccess.getTableAccess().getAroundAssignment_6_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Chair__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Chair__Group__0__Impl
	rule__Chair__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Chair__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getChairAccess().getChairAction_0()); }
	()
	{ after(grammarAccess.getChairAccess().getChairAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Chair__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Chair__Group__1__Impl
	rule__Chair__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Chair__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getChairAccess().getChairKeyword_1()); }
	'Chair'
	{ after(grammarAccess.getChairAccess().getChairKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Chair__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Chair__Group__2__Impl
	rule__Chair__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__Chair__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getChairAccess().getNameAssignment_2()); }
	(rule__Chair__NameAssignment_2)
	{ after(grammarAccess.getChairAccess().getNameAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Chair__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Chair__Group__3__Impl
	rule__Chair__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__Chair__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getChairAccess().getLeftCurlyBracketKeyword_3()); }
	'{'
	{ after(grammarAccess.getChairAccess().getLeftCurlyBracketKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Chair__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Chair__Group__4__Impl
	rule__Chair__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__Chair__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getChairAccess().getGroup_4()); }
	(rule__Chair__Group_4__0)?
	{ after(grammarAccess.getChairAccess().getGroup_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Chair__Group__5
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Chair__Group__5__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Chair__Group__5__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getChairAccess().getRightCurlyBracketKeyword_5()); }
	'}'
	{ after(grammarAccess.getChairAccess().getRightCurlyBracketKeyword_5()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Chair__Group_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Chair__Group_4__0__Impl
	rule__Chair__Group_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Chair__Group_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getChairAccess().getOrderKeyword_4_0()); }
	'order'
	{ after(grammarAccess.getChairAccess().getOrderKeyword_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Chair__Group_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Chair__Group_4__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Chair__Group_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getChairAccess().getOrderAssignment_4_1()); }
	(rule__Chair__OrderAssignment_4_1)
	{ after(grammarAccess.getChairAccess().getOrderAssignment_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__EInt__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EInt__Group__0__Impl
	rule__EInt__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__EInt__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEIntAccess().getHyphenMinusKeyword_0()); }
	('-')?
	{ after(grammarAccess.getEIntAccess().getHyphenMinusKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EInt__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EInt__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__EInt__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEIntAccess().getINTTerminalRuleCall_1()); }
	RULE_INT
	{ after(grammarAccess.getEIntAccess().getINTTerminalRuleCall_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Room__NameAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRoomAccess().getNameEStringParserRuleCall_2_0()); }
		ruleEString
		{ after(grammarAccess.getRoomAccess().getNameEStringParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__FurnitureAssignment_4_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRoomAccess().getFurnitureFurnitureParserRuleCall_4_2_0()); }
		ruleFurniture
		{ after(grammarAccess.getRoomAccess().getFurnitureFurnitureParserRuleCall_4_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Room__FurnitureAssignment_4_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRoomAccess().getFurnitureFurnitureParserRuleCall_4_3_1_0()); }
		ruleFurniture
		{ after(grammarAccess.getRoomAccess().getFurnitureFurnitureParserRuleCall_4_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__NameAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTableAccess().getNameEStringParserRuleCall_2_0()); }
		ruleEString
		{ after(grammarAccess.getTableAccess().getNameEStringParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__XAssignment_4_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTableAccess().getXEIntParserRuleCall_4_1_0()); }
		ruleEInt
		{ after(grammarAccess.getTableAccess().getXEIntParserRuleCall_4_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__YAssignment_5_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTableAccess().getYEIntParserRuleCall_5_1_0()); }
		ruleEInt
		{ after(grammarAccess.getTableAccess().getYEIntParserRuleCall_5_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__AroundAssignment_6_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTableAccess().getAroundChairCrossReference_6_2_0()); }
		(
			{ before(grammarAccess.getTableAccess().getAroundChairEStringParserRuleCall_6_2_0_1()); }
			ruleEString
			{ after(grammarAccess.getTableAccess().getAroundChairEStringParserRuleCall_6_2_0_1()); }
		)
		{ after(grammarAccess.getTableAccess().getAroundChairCrossReference_6_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Table__AroundAssignment_6_3_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getTableAccess().getAroundChairCrossReference_6_3_1_0()); }
		(
			{ before(grammarAccess.getTableAccess().getAroundChairEStringParserRuleCall_6_3_1_0_1()); }
			ruleEString
			{ after(grammarAccess.getTableAccess().getAroundChairEStringParserRuleCall_6_3_1_0_1()); }
		)
		{ after(grammarAccess.getTableAccess().getAroundChairCrossReference_6_3_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Chair__NameAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getChairAccess().getNameEStringParserRuleCall_2_0()); }
		ruleEString
		{ after(grammarAccess.getChairAccess().getNameEStringParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Chair__OrderAssignment_4_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getChairAccess().getOrderEIntParserRuleCall_4_1_0()); }
		ruleEInt
		{ after(grammarAccess.getChairAccess().getOrderEIntParserRuleCall_4_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
