/*
 * generated by Xtext 2.44.0
 */
package geodes.sms.diningroom.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import geodes.sms.diningroom.ide.contentassist.antlr.internal.InternalDiningRoomTextualParser;
import geodes.sms.diningroom.services.DiningRoomTextualGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class DiningRoomTextualParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DiningRoomTextualGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DiningRoomTextualGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getFurnitureAccess().getAlternatives(), "rule__Furniture__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getRoomAccess().getGroup(), "rule__Room__Group__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_4(), "rule__Room__Group_4__0");
			builder.put(grammarAccess.getRoomAccess().getGroup_4_3(), "rule__Room__Group_4_3__0");
			builder.put(grammarAccess.getTableAccess().getGroup(), "rule__Table__Group__0");
			builder.put(grammarAccess.getTableAccess().getGroup_4(), "rule__Table__Group_4__0");
			builder.put(grammarAccess.getTableAccess().getGroup_5(), "rule__Table__Group_5__0");
			builder.put(grammarAccess.getTableAccess().getGroup_6(), "rule__Table__Group_6__0");
			builder.put(grammarAccess.getTableAccess().getGroup_6_3(), "rule__Table__Group_6_3__0");
			builder.put(grammarAccess.getChairAccess().getGroup(), "rule__Chair__Group__0");
			builder.put(grammarAccess.getChairAccess().getGroup_4(), "rule__Chair__Group_4__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getRoomAccess().getNameAssignment_2(), "rule__Room__NameAssignment_2");
			builder.put(grammarAccess.getRoomAccess().getFurnitureAssignment_4_2(), "rule__Room__FurnitureAssignment_4_2");
			builder.put(grammarAccess.getRoomAccess().getFurnitureAssignment_4_3_1(), "rule__Room__FurnitureAssignment_4_3_1");
			builder.put(grammarAccess.getTableAccess().getNameAssignment_2(), "rule__Table__NameAssignment_2");
			builder.put(grammarAccess.getTableAccess().getXAssignment_4_1(), "rule__Table__XAssignment_4_1");
			builder.put(grammarAccess.getTableAccess().getYAssignment_5_1(), "rule__Table__YAssignment_5_1");
			builder.put(grammarAccess.getTableAccess().getAroundAssignment_6_2(), "rule__Table__AroundAssignment_6_2");
			builder.put(grammarAccess.getTableAccess().getAroundAssignment_6_3_1(), "rule__Table__AroundAssignment_6_3_1");
			builder.put(grammarAccess.getChairAccess().getNameAssignment_2(), "rule__Chair__NameAssignment_2");
			builder.put(grammarAccess.getChairAccess().getOrderAssignment_4_1(), "rule__Chair__OrderAssignment_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DiningRoomTextualGrammarAccess grammarAccess;

	@Override
	protected InternalDiningRoomTextualParser createParser() {
		InternalDiningRoomTextualParser result = new InternalDiningRoomTextualParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DiningRoomTextualGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DiningRoomTextualGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
