/*
 * generated by Xtext 2.44.0
 */
package geodes.sms.diningroom.ui;

import com.google.inject.Injector;
import diningRoomTextual.ui.internal.DiningRoomTextualActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DiningRoomTextualExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(DiningRoomTextualActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		DiningRoomTextualActivator activator = DiningRoomTextualActivator.getInstance();
		return activator != null ? activator.getInjector(DiningRoomTextualActivator.GEODES_SMS_DININGROOM_DININGROOMTEXTUAL) : null;
	}

}
