/*
 * generated by Xtext 2.44.0
 */
package holt.travis.ift6253.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import holt.travis.ift6253.MindMapRuntimeModule;
import holt.travis.ift6253.MindMapStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MindMapIdeSetup extends MindMapStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MindMapRuntimeModule(), new MindMapIdeModule()));
	}
	
}
