// name the grammar and build on xtext lexing
grammar holt.travis.ift6253.MindMap with org.eclipse.xtext.common.Terminals

// infer new ecore metamodel from this grammar
generate mindMap "http://www.travis.holt/ift6253/MindMap"


// entry rule
MindMap:
	'mindmap' name=ID ('(' tags+=AnyTag (',' tags+=AnyTag)* ')')? '{'
		roots+=Topic* // containment feature
	'}'
;
	
Topic:
	(deeper?='->' | '-') // boolean assignment
	name=ID 
	('<' tags+=[Tag] '>')*
	('(' priority=Priority ')')?
	('*' related+=[Topic])* 
	('{'
		('description' ':' description=STRING)?
		(view=View)?
		children+=Topic* 
	'}')?
;

Tag:
	'tag' name=ID
;

// not necessary, just for learning about the mechanism
@Deprecated
LabelTag returns Tag:
	'label' name=ID
;

AnyTag returns Tag:
	Tag | LabelTag
;


View:
	// force object creation 
	{View} 'view' '{'
		('color' ':' color=STRING)?
	'}'
;

enum Priority:
	HIGH = 'H' |
	MEDIUM = 'M' |
	LOW = 'L'
;