/*
 * generated by Xtext 2.44.0
 */
package holt.travis.ift6253;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MindMapRuntimeModule extends AbstractMindMapRuntimeModule {
}
