/**
 * generated by Xtext 2.44.0
 */
package geodes.sms.diningroom.formatting2;

import DiningRoom.Furniture;
import DiningRoom.Room;
import com.google.inject.Inject;
import geodes.sms.diningroom.services.DiningRoomTextualGrammarAccess;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;

@SuppressWarnings("all")
public class DiningRoomTextualFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private DiningRoomTextualGrammarAccess _diningRoomTextualGrammarAccess;

  protected void _format(final Room room, @Extension final IFormattableDocument document) {
    EList<Furniture> _furniture = room.getFurniture();
    for (final Furniture furniture : _furniture) {
      document.<Furniture>format(furniture);
    }
  }

  @XbaseGenerated
  public void format(final Object room, final IFormattableDocument document) {
    if (room instanceof XtextResource) {
      _format((XtextResource)room, document);
      return;
    } else if (room instanceof Room) {
      _format((Room)room, document);
      return;
    } else if (room instanceof EObject) {
      _format((EObject)room, document);
      return;
    } else if (room == null) {
      _format((Void)null, document);
      return;
    } else if (room != null) {
      _format(room, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(room, document).toString());
    }
  }
}
