/*
 * generated by Xtext 2.44.0
 */
package holt.travis.ift6253.tests

import com.google.inject.Inject
import holt.travis.ift6253.mindMap.MindMap
import holt.travis.ift6253.mindMap.MindMapPackage
import holt.travis.ift6253.validation.MindMapValidator
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(MindMapInjectorProvider)
class MindMapParsingTest {
	@Inject
	ParseHelper<MindMap> parseHelper

	@Inject
	extension ValidationTestHelper

	@Test
	def void loadModelEmptyMindMap() {
		parseHelper.parse('''
			mindmap mde_course {}
		''').assertNoErrors()
	}

	@Test
	def void loadModelWithOneTopic() {
		parseHelper.parse('''
			mindmap mde_course {
				- dummy {}
			}
		''').assertNoErrors()
	}

	@Test
	def void loadModelWithOneTopicWithoutBraces() {
		parseHelper.parse('''
			mindmap mde_course {
				- dummy
			}
		''').assertNoErrors()
	}

	@Test
	def void loadModelWithOneTag() {
		parseHelper.parse('''
			mindmap mde_course (tag TAG1) {}
		''').assertNoErrors()
	}

	@Test
	def void loadModelWithMultipleTags() {
		parseHelper.parse('''
			mindmap mde_course (tag TAG1, tag TAG2) {}
		''').assertNoErrors()
	}

	@Test
	def void loadModelWithTaggedTopic() {
		parseHelper.parse('''
			mindmap mde_course (tag DUMMY) {
				- my_topic <DUMMY>
			}
		''').assertNoErrors()
	}

	@Test
	def void loadModelWithMultiTaggedTopic() {
		parseHelper.parse('''
			mindmap mde_course (tag DUMMY1, tag DUMMY2) {
				- my_topic <DUMMY1> <DUMMY2>
			}
		''').assertNoErrors()
	}

	@Test
	def void loadModelWithMultipleRoots() {
		parseHelper.parse('''
			mindmap mde_course {
				- dummy1
				- dummy2
			}
		''').assertNoErrors()
	}

	@Test
	def void loadModelWithDeeperRootFails() {
		parseHelper.parse('''
			mindmap mde_course {
				-> dummy
			}
		''').assertError(
			MindMapPackage.Literals.TOPIC, 
			MindMapValidator.DEEPER_AT_ROOT
		)
	}

	@Test
	def void loadModelWithDeeperTopic() {
		parseHelper.parse('''
			mindmap mde_course {
				- parent {
					-> deeper_child
				}
			}
		''').assertNoErrors()
	}
	
	@Test
	def void loadModelWithTopicDescription() {
		parseHelper.parse('''
			mindmap mde_course {
				- topic {
					description: "dummy desc"
				}
			}
		''').assertNoErrors()
	}
	
	@Test
	def void loadModelWithViewInfo() {
		parseHelper.parse('''
			mindmap mde_course {
				- topic {
					view {
						color: "#0000FF"
					}
				}
			}
		''').assertNoErrors()
	}
	
	@Test
	def void loadModelWithInvalidColorFails() {
		parseHelper.parse('''
			mindmap mde_course {
				- topic {
					view {
						color: "#INVALID_COLOR"
					}
				}
			}
		''').assertError(
			MindMapPackage.Literals.VIEW, 
			MindMapValidator.INVALID_COLOR
		)
	}
	
	
	@Test
	def void loadModelWithAllFeatures() {
		parseHelper.parse('''
			mindmap mde_course (tag STAR, tag QUESTION) {
			    - class (H) {
			        description: "text description of topic"
			        view {
			            color: "#0000FF"
			        }
			        -> attendance <STAR> <QUESTION> (H)
			        - active_learning {
			            - take_notes
			            - clarify_with_chat
			        }
			    }
			    - work (M) {
			        - readings (L) {
			            -> todo
			            -> done
			            - projects {
			                - main <STAR> {
			                    -> find_partner {
			                        - suggest_topic <QUESTION>
			                        -> talk_to_someone
			                    }
			                }
			            }
			        }
			        - homework
			        - tool_tutorials
			    }
			}
		''').assertNoErrors()
	}
}
