/*
 * generated by Xtext 2.44.0
 */
package geodes.sms.diningroom;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DiningRoomTextualRuntimeModule extends AbstractDiningRoomTextualRuntimeModule {
}
