/*
 * generated by Xtext 2.44.0
 */
package geodes.sms.diningroom;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DiningRoomTextualStandaloneSetup extends DiningRoomTextualStandaloneSetupGenerated {

	public static void doSetup() {
		new DiningRoomTextualStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
