/*
 * generated by Xtext 2.44.0
 */
package geodes.sms.diningroom.ide;


/**
 * Use this class to register ide components.
 */
public class DiningRoomTextualIdeModule extends AbstractDiningRoomTextualIdeModule {
}
