/*
 * generated by Xtext 2.44.0
 */
package holt.travis.ift6253.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MindMapUiModule extends AbstractMindMapUiModule {

	public MindMapUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
