/*
 * generated by Xtext 2.44.0
 */
package geodes.sms.diningroom.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDiningRoomTextualScopeProvider extends DelegatingScopeProvider {
}
