/*
 * generated by Xtext 2.44.0
 */
package geodes.sms.diningroom.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DiningRoomTextualUiModule extends AbstractDiningRoomTextualUiModule {

	public DiningRoomTextualUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
